Add drop_duplicates for dims
pydata/xarray pull request #5239
Opened 2021-05-01 03:23 UTC by ahuang11

Ruined https://github.com/pydata/xarray/pull/5089 with reverting so remaking the PR for just dims

- [ ] Closes #xxxx
- [x] Tests added
- [x] Passes `pre-commit run --all-files`
- [x] User visible changes (including notable bug fixes) are documented in `whats-new.rst`
- [x] New functions/methods are listed in `api.rst`

2021-05-01 03:23 UTC, pep8speaks commented
Hello @ahuang11! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`xarray/tests/test_dataarray.py`](https://github.com/pydata/xarray/blob/4cb67dca15d3a70d4f72e2093141efae9059875e/xarray/tests/test_dataarray.py):

> [Line 7422:1](https://github.com/pydata/xarray/blob/4cb67dca15d3a70d4f72e2093141efae9059875e/xarray/tests/test_dataarray.py#L7422): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 0

2021-05-01 04:07 UTC, shoyer approved these changes

2021-05-01 17:20 UTC, shoyer requested changes
Actually -- there is still one unresolved design concern here.

If you drop duplicates over multiple variables at once, what dimensions should the result have? In particular -- should it have the original dimensions, or should all dimensions involved be combined into one?

The latter might seem a little crazy now, but would make more sense once we allow dropping over multi-dimensional variables.

If we really want to avoid any possible controversy here, it might be best to stick to only supporting one variable for now, too.

2021-05-01 19:39 UTC, max-sixty commented
The docs are failing with:

```
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/5239/xarray/core/dataarray.py:docstring of xarray.core.dataarray.DataArray.drop_duplicates:3: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/xray/checkouts/5239/xarray/core/dataarray.py:docstring of xarray.core.dataarray.DataArray.drop_duplicates:4: WARNING: Block quote ends without a blank line; unexpected unindent.
looking for now-outdated files... none found
```

2021-05-01 19:45 UTC, max-sixty commented
> If you drop duplicates over multiple variables at once, what dimensions should the result have? In particular -- should it have the original dimensions, or should all dimensions involved be combined into one?
> 
> The latter might seem a little crazy now, but would make more sense once we allow dropping over multi-dimensional variables.
> 
> If we really want to avoid any possible controversy here, it might be best to stick to only supporting one variable for now, too.

For me this case supports consistent behavior over any number of dims! Which would mean rejecting the "stack only if you supply exactly ndims" proposal.

Completely fine with restricting to one dim for the moment and seeing how that goes (it's always possible to pass `.drop_duplicates_coords(dim1).drop_duplicates_coords(dim2)`.

Were we going with `drop_duplicates` or `drop_duplicates_coords`? No strong view from me at all.

2021-05-01 19:51 UTC, keewis commented on xarray/core/dataarray.py
> +        dims : dimension label or sequence of labels, optional
```suggestion
        dims : hashable or sequence of hashable, optional
```

2021-05-01 19:54 UTC, keewis commented
the docs build can probably be fixed by adding newlines before the section headers ("Parameters" / "Returns")

2021-05-12 16:33 UTC, max-sixty commented
@ahuang11 we discussed this on the core team call. People are excited to merge this, and appreciate you bearing with the changes.

I suggested that we narrow this even further to one dimension and merge, so we can benefit from this now and consider additions from there. Would that be OK with you?

2021-05-12 16:47 UTC, ahuang11 commented
Sure.

What's the reasoning for a single dimension?

On Wed, May 12, 2021, 11:34 AM Maximilian Roos ***@***.***>
wrote:

> @ahuang11 <https://github.com/ahuang11> we discussed this on the core
> team call. People are excited to merge this, and appreciate you bearing
> with the changes.
>
> I suggested that we narrow this even further to one dimension and merge,
> so we can benefit from this now and consider additions from there. Would
> that be OK with you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pydata/xarray/pull/5239#issuecomment-839925301>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADU7FFSS2IQ5QP7BYG4OCWLTNKUXXANCNFSM4353OVNA>
> .
>

2021-05-12 16:54 UTC, max-sixty commented
@shoyer could I confirm that limiting to a single dimension satisfies this? You say "multiple variables" here. I mentioned a single dimension on the call but maybe wasn't clear.

> If you drop duplicates over multiple variables at once, what dimensions should the result have? In particular -- should it have the original dimensions, or should all dimensions involved be combined into one?
> 
> The latter might seem a little crazy now, but would make more sense once we allow dropping over multi-dimensional variables.
> 
> If we really want to avoid any possible controversy here, it might be best to stick to only supporting one variable for now, too.

2021-05-13 03:25 UTC, ahuang11 commented
Dont understand this
```
xarray/core/dataarray.py:4605: error: Argument 1 to "isel" of "DataArray" has incompatible type "Dict[str, Any]"; expected "Optional[Mapping[Hashable, Any]]"  [arg-type]
Found 1 error in 1 file (checked 140 source files)
```

`self.isel(indexes)`

2021-05-13 03:41 UTC, max-sixty commented on xarray/core/dataarray.py
> +        dim: str,
```suggestion
        dim: Hashable,
```

2021-05-13 03:52 UTC, max-sixty commented on xarray/core/dataarray.py
> +        indexes = {}
```suggestion
```

2021-05-13 03:53 UTC, max-sixty commented on xarray/core/dataarray.py
> +        indexes[dim] = ~self.get_index(dim).duplicated(keep=keep)
```suggestion
        indexes = {dim: ~self.get_index(dim).duplicated(keep=keep)}
```

2021-05-13 17:47 UTC, dcherian commented
> @shoyer could I confirm that limiting to a single dimension satisfies this? You say "multiple variables" here. I mentioned a single dimension on the call but maybe wasn't clear.

@shoyer can you kindly merge this if you're happy with it?

2021-05-15 17:46 UTC, max-sixty commented
Merging but I or @ahuang11 can do any follow-ups.

Thank you v much @ahuang11 — appreciate this was a lot of work and happy to have you contribute such a good feature.

2021-05-15 17:46 UTC, merged