Added driver parameter for h5netcdf
pydata/xarray pull request #8360
Opened 2023-10-23 15:14 UTC by zequihg50

Following [this change in h5netcdf](https://github.com/h5netcdf/h5netcdf/pull/220), allow xarray to open HDF5 files using the ros3 VFD from HDF5.

2023-10-31 17:02 UTC, kmuehlbauer commented
@zequihg50 This is looking good to me. 

I've almost no experience with cloud access data, so please bear with me. It would be great if there is a permanent endpoint somewhere, or if it could be emulated within CI. Not only here, but also over at h5netcdf. Thanks!

2023-10-31 17:06 UTC, kmuehlbauer commented
The only thing we might have to think about is, that this will only take effect with the next h5netcdf release. For all other versions this will silently not take `driver` into account and use the current `h5pyd` approach.

2023-11-07 09:12 UTC, zequihg50 commented
Now that the pull request for h5netcdf is [merged](https://github.com/h5netcdf/h5netcdf/pull/220), is there anything missing here? For testing I have suggested to use a file from netCDF [examples](https://www.unidata.ucar.edu/software/netcdf/examples/OMI-Aura_L2-example.nc).

2023-11-07 20:02 UTC, kmuehlbauer commented
> Now that the pull request for h5netcdf is [merged](https://github.com/h5netcdf/h5netcdf/pull/220), is there anything missing here? For testing I have suggested to use a file from netCDF [examples](https://www.unidata.ucar.edu/software/netcdf/examples/OMI-Aura_L2-example.nc).

Yes, a test would be nice indeed. Also, as mentioned over in #8423, it would be nice to distribute additional kwargs to the backend.

2023-11-09 07:22 UTC, kmuehlbauer requested changes
@zequihg50 I've added a couple of suggestions. Please let me know, if you can add the needed changes and a test.

Please also add an entry to [whats-new.rst](https://github.com/pydata/xarray/blob/main/doc/whats-new.rst).

2023-11-09 07:22 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +        driver=None,
We might want to enable `driver_kwds`, too. See https://docs.h5py.org/en/stable/high/file.html#file-drivers. With that users would be able to correctly specify eg. authentication.

2023-11-09 07:22 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +            "driver": driver,
Here we would need to update kwargs, adding `driver_kwds` to `kwargs` if `driver` is given.

2023-11-09 07:22 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +        driver=None,
Here too, add `driver_kwds`.

2023-11-09 07:22 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +            driver=driver,
Here too, add `driver_kwds`.

2023-11-12 14:17 UTC, kmuehlbauer reviewed
@zequihg50 I've added some code suggestion how to avoid some issues with CachingFileManager.

2023-11-12 14:17 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +        driver=None,
```suggestion
        driver=None,
        driver_kwds=None,
```

2023-11-12 14:17 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +        driver=None,
```suggestion
        driver=None,
        driver_kwds=None,
```

2023-11-12 14:17 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
>          }
```suggestion
        }
        if driver_kwds is not None:
            kwargs.update(driver_kwds)
```

2023-11-12 14:17 UTC, kmuehlbauer commented on xarray/backends/h5netcdf_.py
> +            driver=driver,
```suggestion
            driver=driver,
            driver_kwds=driver_kwds,
```

2023-11-13 09:47 UTC, kmuehlbauer commented
@zequihg50 Thanks for adding the test. The test will only work for h5netcdf >= 1.3.0, though.


@dcherian Do we have to check for h5netcdf-version here? Or does it make sense to just let the test run if h5netcdf >= 1.3.0 is installed?

2023-11-13 20:21 UTC, dcherian commented
> Or does it make sense to just let the test run if h5netcdf >= 1.3.0 is installed?

:+1: @zequihg50 we use this type of decorator to run a test only if the version is greater than a min version: https://github.com/pydata/xarray/blob/0c1ad54d67015437b507a33305a30fa2cb1f5398/xarray/tests/__init__.py#L93-L97

2023-11-15 06:48 UTC, kmuehlbauer commented
LGTM! @zequihg50 Please merge xarray latest main into this PR branch and add an entry to https://github.com/pydata/xarray/blob/main/doc/whats-new.rst to make this enhancement visible.

2023-11-15 17:01 UTC, dcherian commented
Thanks @zequihg50 and @kmuehlbauer

2023-11-15 17:05 UTC, merged

2023-11-15 17:22 UTC, kmuehlbauer commented
Thanks @zequihg50 for pushing this through!