Refactor datetime and timedelta encoding for increased robustness
pydata/xarray pull request #9498
Opened 2024-09-15 14:47 UTC by spencerkclark

This PR makes the proposed updates in https://github.com/pydata/xarray/issues/9488#issuecomment-2351149546, removing the guard against overflow in dtype casting.  In so doing I have added units checking / potential modification to the cftime code path to bring things up to speed with the NumPy code path, and also added a regression test for #9134.

Now we more robustly raise an error in the case of chunked times where an integer dtype encoding is specified, but the units do not allow for an accurate roundtrip.  This was the original intent of the code, though we can also discuss whether it is better to warn instead of raise in this instance—one way or another this would also make it safer to switch the default units with which we encode chunked times (#9154).

As @kmuehlbauer notes, this would be another way to fix #9488; in some ways it is complementary to #9497.

- [x] Closes #9134
- [x] Tests added
- [ ] User visible changes (including notable bug fixes) are documented in `whats-new.rst`

2024-09-16 20:35 UTC, langmore reviewed
After line 332, we could have an `int32` value for `num_dates` (e.g. if the user provided an `int32` value to begin with).  This will be passed down to `_decode_datetime_with_pandas`, which, upon calling `pd.to_timedelta(flat_num_dates.min(), time_units)` will raise `OutOfBoundsTimedelta: Cannot cast 24 from h to 'ns' without overflow` due to pandas not handling the `int32` first argument. This is preventable by casting `num_dates` to `int64`.

I believe this is related to https://github.com/pandas-dev/pandas/issues/56996

2024-09-18 02:06 UTC, spencerkclark commented
Thanks for pointing this out @langmore.  Indeed I think we actually have tests that would fail because of this in our suite, but we don't (yet) have a CI environment that has NumPy >= 2, but no cftime.  In other words the fact that we can fall back to decoding times with cftime masks this.

Your suggested workaround makes sense to me; we may just want to make sure that we cast signed integers to `int64` and unsigned integers to `uint64` to avoid overflow (and avoid doing any casting for floats).  If you'd like, I think we'd be happy to take a PR; I can also take care of it if you prefer.  Unfortunately [my attempt to fix this upstream](https://github.com/pandas-dev/pandas/pull/57984) stalled.

2024-09-18 16:49 UTC, langmore commented
> Thanks for pointing this out @langmore. Indeed I think we actually have tests that would fail because of this in our suite, but we don't (yet) have a CI environment that has NumPy >= 2, but no cftime. In other words the fact that we can fall back to decoding times with cftime masks this.
> 
> Your suggested workaround makes sense to me; we may just want to make sure that we cast signed integers to `int64` and unsigned integers to `uint64` to avoid overflow (and avoid doing any casting for floats). If you'd like, I think we'd be happy to take a PR; I can also take care of it if you prefer. Unfortunately [my attempt to fix this upstream](https://github.com/pandas-dev/pandas/pull/57984) stalled.

@spencerkclark I won't have time to fix this, since we're also falling back on cftime so it works for us, for now.

2024-09-19 00:04 UTC, spencerkclark commented
No worries @langmore—I went ahead with something along the lines of your suggested fix in #9518.

2025-03-07 16:41 UTC, dcherian commented
Is this one ready to go in?

2025-03-08 18:02 UTC, spencerkclark commented
OK I think things are ready from my perspective—new zarr test failures are unrelated—though it would probably be good for @kmuehlbauer to give this a once over when he has a chance.  Some of the changes here interacted with changes made in #10050.  Specifically, this PR restores the responsibility of final dtype casting to later in the encoding chain, so we need to retain the `"dtype"` key in the `encoding`.  In general though, I think this slightly simplifies the logic in the datetime and timedelta coders, which is probably a good thing.  See 2970532 for the necessary updates.

2025-03-15 14:50 UTC, kmuehlbauer requested changes
Thanks @spencerkclark, this looks really good! I've added two suggestions to fix minor issues.

2025-03-15 14:50 UTC, kmuehlbauer commented on xarray/coding/times.py
> +                )
The assignment needs to go after the warning, otherwise the warning would return same for "units" and "new_units".

```suggestion
                emit_user_level_warning(
                    f"Times can't be serialized faithfully to int64 with requested units {units!r}. "
                    f"Serializing with units {new_units!r} instead. "
                    f"Set encoding['dtype'] to floating point dtype to serialize with units {units!r}. "
                    f"Set encoding['units'] to {new_units!r} to silence this warning ."
                )
                units = new_units
```

2025-03-15 14:50 UTC, kmuehlbauer commented on xarray/coding/times.py
> -        needed_unit, data_ref_date = _unpack_time_unit_and_ref_date(data_units)
:+1: for refactoring out into separate function.

2025-03-15 14:50 UTC, kmuehlbauer commented on xarray/coding/times.py
> +                floor_division = True
Already set above. Maybe remove above, so all assignments are in one place.

2025-03-15 15:59 UTC, kmuehlbauer commented on doc/whats-new.rst
> +  trip (:pull:`9498`). By `Spencer Clark
Is this due to a merge conflict? Seems like it is missing the rest of the github link.

2025-03-16 00:23 UTC, spencerkclark reviewed
Thanks for the review @kmuehlbauer—very helpful comments!  Things should hopefully be all good now.

2025-03-16 00:23 UTC, spencerkclark commented on doc/whats-new.rst
> +  trip (:pull:`9498`). By `Spencer Clark
Ah yes, that's why the docs build is failing—thanks.  Indeed looks like I didn't fully fix things in https://github.com/pydata/xarray/pull/9498/commits/74a85b022f740986573cb257b9cd169d15cec14c.

2025-03-16 00:23 UTC, spencerkclark commented on xarray/coding/times.py
> +                )
Important catch—thanks!

2025-03-18 06:48 UTC, kmuehlbauer approved these changes
I think this is good to go now Thanks @spencerkclark, those are really tricky issues solved here!

2025-03-18 13:12 UTC, merged